//X = wall, O = skip, P = pac man, ' ' = food
//Ghosts: b = blue, o = orange, p = pink, r = red, C = cherry, c = small cherry
const tileMap1 = [
    "XXXXXXXXXXXXXXXXXXX",
    "X        X        X",
    "X XXCXXX X XXXcXX X",
    "X                 X",
    "X XX X XXXXX X XX X",
    "X c  X       X    X",
    "XXXX XXXX XXXX XXXX",
    "O  X X       X X  O",
    "XXXX X XXrXX X XXXX",
    "O c     bpo       O",
    "XXXX X XXXXX X XXXX",
    "O  X X       X X  O",
    "XXXX X XXXXX X XXXX",
    "X        X   C    X",
    "X XX XXX X XXX XX X",
    "X  X     P     X  X",
    "XX X X XXXXX X X XX",
    "X    X   X   X C  X",
    "X XXXXXX X XXXXXX X",
    "X                 X",
    "XXXXXXXXXXXXXXXXXXX"
];

const tileMap2 = [
    "XXXXXXXXXXXXXXXXXXX",
    "X   X         X   X",
    "X X X XXXXXXX X X X",
    "X X             X X",
    "X X XXX XXX XXX X X",
    "X                 X",
    "XXX XXX  X  XXX XXX",
    "O                 O",
    "XXX X XXrXX XX X XXX",
    "O   b    p    o   O",
    "XXX X XXXXXXX X XXX",
    "O   X    P    X   O",
    "XXX X XXXXXXX X XXX",
    "X                 X",
    "X X XXX XXX XXX X X",
    "X X             X X",
    "X X XXXXX XXXXX X X",
    "X   X   X X   X   X",
    "X XXX XXX XXX XXX X",
    "X                 X",
    "XXXXXXXXXXXXXXXXXXX",
];

const tileMap3 = [
    "XXXXXXXXXXXXXXXXXXX",
    "X                 X",
    "X XX XXXXXXXXX XX X",
    "X                 X",
    "X XXXXX  X  XXXXX X",
    "X                 X",
    "XXXXXXX XXX XXXXXXX",
    "O                 O",
    "XXXX X XXrXX X XXXX",
    "O   b    p    o   O",
    "XXXX X XXXXX X XXXX",
    "O   X    P    X   O",
    "XXXX X XXXXX X XXXX",
    "X                 X",
    "X XXXXX  X  XXXXX X",
    "X                 X",
    "X XX XXXXXXXXX XX X",
    "X                 X",
    "X XXXXX XXX XXXXX X",
    "X                 X",
    "XXXXXXXXXXXXXXXXXXX",
];

const tileMap4 = [
    "XXXXXXXXXXXXXXXXXXX",
    "X   X     X     X X",
    "X X X XXX X XXX X X",
    "X X             X X",
    "X X XXX XXX XXX X X",
    "X   X       X   X X",
    "XXX XXXXX XXXXX XXX",
    "O                 O",
    "XXX X XXrXX XX X XXX",
    "O   b    p    o   O",
    "XXX X XXXXXXX X XXX",
    "O   X    P    X   O",
    "XXX X XXXXXXX X XXX",
    "X   X       X   X X",
    "X X XXX XXX XXX X X",
    "X X             X X",
    "X X X XXX XXX X X X",
    "X   X   X X   X   X",
    "X XXXXX X X XXXXX X",
    "X                 X",
    "XXXXXXXXXXXXXXXXXXX"
];

const tileMap5 = [
    "XXXXXXXXXXXXXXXXXXX",
    "X      c C c      X",
    "X XX XXX X XXX XX X",
    "X XX             XX",
    "X    X XXXXX X    X",
    "X XX X       X XX X",
    "X XX XXXX  XXX XX X",
    "O    X  rpb  X    O",
    "XXXX X XXXXX X XXXX",
    "X    X   o   X    X",
    "X XX XXXXXXXX XX  X",
    "X XX    C       XXX",
    "X XXXX XXXXXXX  XXX",
    "X    X   X   X    X",
    "XX X XXX X XXX X XX",
    "X        P        X",
    "X XXXX XXXXXXX  XXX",
    "X    X   X   X    X",
    "X XX X XXXXX X XX X",
    "X      c   c      X",
    "XXXXXXXXXXXXXXXXXXX",
];

const tileMap6 = [
    "XXXXXXXXXXXXXXXXXXX",
    "X      X X      C X",
    "X XX XX   XX XXXXXX",
    "X                 X",
    "X XX X XXXXX X XX X",
    "X  X X   c   X X  X",
    "X XX X XXXXX X XX X",
    "O    X   r   X    O",
    "XXXX XXXXXXXX  XXXX",
    "X    b  p o        X",
    "XXXX X XXXXX X XXXX",
    "O    X       X    O",
    "X XX X XXXXX X XX X",
    "X XX     P     XX X",
    "X    X XXXXX X    X",
    "X XX X       X XX X",
    "X XX XXXX XXXX XX X",
    "X    X   C   X    X",
    "X XX XXXXXXXXXX X X",
    "X c           c   X",
    "XXXXXXXXXXXXXXXXXXX",
];

const tileMap7 = [
    "XXXXXXXXXXXXXXXXXXX",
    "X    c     c     CX",
    "X XX XXXXXXXX XX XX",
    "X                 X",
    "X XXXXX X X XXXXX X",
    "X       X X       X",
    "X XXXXX X X XXXXX X",
    "O  r   X   X   p  O",
    "X XXX XXXXXXX XXX X",
    "X X             X X",
    "X X XXXXXXXXXXX X X",
    "X X     P       X X",
    "X XXXXXXXXXXXXXXX X",
    "X                 X",
    "X XX XXXXXXXX XX XX",
    "X   X    o    X   X",
    "XXX XXXXXXXXXXX XXX",
    "X       b         X",
    "X XX XXXXXXXX XX XX",
    "X    C     C     cX",
    "XXXXXXXXXXXXXXXXXXX",
];