//X = wall, O = skip, P = pac man, ' ' = food
//Ghosts: b = blue, o = orange, p = pink, r = red
const tileMap1 = [
    "XXXXXXXXXXXXXXXXXXX",
    "X        X        X",
    "X XXCXXX X XXXcXX X",
    "X                 X",
    "X XX X XXXXX X XX X",
    "X c  X       X    X",
    "XXXX XXXX XXXX XXXX",
    "O  X X       X X  O",
    "XXXX X XXrXX X XXXX",
    "O c     bpo       O",
    "XXXX X XXXXX X XXXX",
    "O  X X       X X  O",
    "XXXX X XXXXX X XXXX",
    "X        X   C    X",
    "X XX XXX X XXX XX X",
    "X  X     P     X  X",
    "XX X X XXXXX X X XX",
    "X    X   X   X C  X",
    "X XXXXXX X XXXXXX X",
    "X                 X",
    "XXXXXXXXXXXXXXXXXXX"
];

const tileMap2 = [
    "XXXXXXXXXXXXXXXXXXX",
    "X   X         X   X",
    "X X X XXXXXXX X X X",
    "X X             X X",
    "X X XXX XXX XXX X X",
    "X                 X",
    "XXX XXX  X  XXX XXX",
    "O                 O",
    "XXX X XXrXX XX X XXX",
    "O   b    P    o   O",
    "XXX X XXXXXXX X XXX",
    "O   X    p    X   O",
    "XXX X XXXXXXX X XXX",
    "X                 X",
    "X X XXX XXX XXX X X",
    "X X             X X",
    "X X XXXXX XXXXX X X",
    "X   X   X X   X   X",
    "X XXX XXX XXX XXX X",
    "X                 X",
    "XXXXXXXXXXXXXXXXXXX",
];

const tileMap3 = [
    "XXXXXXXXXXXXXXXXXXX",
    "X                 X",
    "X XX XXXXXXXXX XX X",
    "X                 X",
    "X XXXXX  X  XXXXX X",
    "X                 X",
    "XXXXXXX XXX XXXXXXX",
    "O                 O",
    "XXXX X XXrXX X XXXX",
    "O   b    P    o   O",
    "XXXX X XXXXX X XXXX",
    "O   X    p    X   O",
    "XXXX X XXXXX X XXXX",
    "X                 X",
    "X XXXXX  X  XXXXX X",
    "X                 X",
    "X XX XXXXXXXXX XX X",
    "X                 X",
    "X XXXXX XXX XXXXX X",
    "X                 X",
    "XXXXXXXXXXXXXXXXXXX",
];

const tileMap4 = [
    "XXXXXXXXXXXXXXXXXXX",
    "X   X     X     X X",
    "X X X XXX X XXX X X",
    "X X             X X",
    "X X XXX XXX XXX X X",
    "X   X       X   X X",
    "XXX XXXXX XXXXX XXX",
    "O                 O",
    "XXX X XXrXX XX X XXX",
    "O   b    P    o   O",
    "XXX X XXXXXXX X XXX",
    "O   X    p    X   O",
    "XXX X XXXXXXX X XXX",
    "X   X       X   X X",
    "X X XXX XXX XXX X X",
    "X X             X X",
    "X X X XXX XXX X X X",
    "X   X   X X   X   X",
    "X XXXXX X X XXXXX X",
    "X                 X",
    "XXXXXXXXXXXXXXXXXXX"
];